# Generated by Django 5.0.4 on 2024-04-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='DinnerTime',
            field=models.TimeField(),
        ),
    ]
