# Generated by Django 5.0.4 on 2024-04-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human_Health', '0002_alter_food_dinnertime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
